---
exclude: "/3rdParty/"

default_language_version:
  node: "14.15.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: mixed-line-ending
      - id: pretty-format-json
        exclude: ()
        args: ["--autofix"]
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.11
    hooks:
      - id: forbid-crlf
      - id: remove-crlf

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: main.yml

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
    name: autopep8-default
    exclude: ()

  - repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: master
    hooks:
      - id: clang-format
      - id: cpplint
        args: [--filter=-legal/copyright]
      - id: cppcheck
        args: [--std=c++11, --std=c++14, --language=c++]
